wandb_version: 1

use_graph:
  desc: null
  value: false
lr:
  desc: null
  value: 0.0001
dropout:
  desc: null
  value: 0.0
cuda:
  desc: null
  value: 0
epochs:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 0.0
optimizer:
  desc: null
  value: adam
momentum:
  desc: null
  value: 0.995
patience:
  desc: null
  value: 5
seed:
  desc: null
  value: 42
log_freq:
  desc: null
  value: 1
save:
  desc: null
  value: 0
save_dir:
  desc: null
  value: null
sweep_c:
  desc: null
  value: 0
lr_reduce_freq:
  desc: null
  value: 5000
gamma:
  desc: null
  value: 0.75
grad_clip:
  desc: null
  value: null
min_epochs:
  desc: null
  value: 2
mixed_precision:
  desc: null
  value: fp16
gradient_accumulation_steps:
  desc: null
  value: 1
lorentz_pos_margin:
  desc: null
  value: 0.0
lorentz_neg_margin:
  desc: null
  value: 0.8
euclid_pos_margin:
  desc: null
  value: 1.0
euclid_neg_margin:
  desc: null
  value: 0.8
max_txt_len:
  desc: null
  value: 35
negative_all_rank:
  desc: null
  value: false
alpha:
  desc: null
  value: 0.4
queue_size:
  desc: null
  value: 75000
batch_size:
  desc: null
  value: 50
eval_freq:
  desc: null
  value: 1450
weight_i2t:
  desc: null
  value: 0.5
enable_log:
  desc: null
  value: true
use_margin_loss:
  desc: null
  value: false
use_graph_loss:
  desc: null
  value: false
use_entailment_loss:
  desc: null
  value: false
hyp_margin_loss_weight:
  desc: null
  value: 0.0
num_proj_layers:
  desc: null
  value: 6
proj_layer_hidden_sizes:
  desc: null
  value: 64
normalize_text_embed:
  desc: null
  value: false
normalize_image_embed:
  desc: null
  value: false
shared_proj_layers:
  desc: null
  value: false
use_itm_head:
  desc: null
  value: true
use_fused_features:
  desc: null
  value: false
use_root:
  desc: null
  value: false
graph_hidden_channels:
  desc: null
  value: 512
model_ckt:
  desc: null
  value: lavis-blip-itm-base-flickr
manifold:
  desc: null
  value: euclidean
curv:
  desc: null
  value: 1.0
atol:
  desc: null
  value: 0.1
rtol:
  desc: null
  value: 0.1
temp:
  desc: null
  value: 0.07
clip_radius:
  desc: null
  value: 1.25
vision_trainable_blocks:
  desc: null
  value: 6
text_trainable_blocks:
  desc: null
  value: 12
num_vision_hidden_states:
  desc: null
  value: 1
num_text_hidden_states:
  desc: null
  value: 1
ft_out:
  desc: null
  value: 768
curv_learnable:
  desc: null
  value: false
freeze_embedding:
  desc: null
  value: true
fourier:
  desc: null
  value: false
use_last_signal:
  desc: null
  value: false
use_signal_loss:
  desc: null
  value: true
compress_method:
  desc: null
  value: PiToMe
distil:
  desc: null
  value: false
r:
  desc: null
  value: 0.925
dataset:
  desc: null
  value: flickr
cache_dir:
  desc: null
  value: /mnt/data/mount_4TBSSD/nmduy/pitome/.cache
num_latents:
  desc: null
  value: 12
d_latents:
  desc: null
  value: 1024
num_blocks:
  desc: null
  value: 1
num_self_attends_per_block:
  desc: null
  value: 3
num_cross_attention_heads:
  desc: null
  value: 4
num_self_attention_heads:
  desc: null
  value: 4
cross_attention_widening_factor:
  desc: null
  value: 4
attention_probs_dropout_prob:
  desc: null
  value: 0.2
num_hidden_states:
  desc: null
  value: 2
use_first_layers:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705631846.967617
    t:
      1:
      - 1
      - 11
      - 33
      - 41
      - 49
      - 51
      - 55
      - 63
      - 71
      - 98
      2:
      - 1
      - 11
      - 33
      - 41
      - 49
      - 51
      - 55
      - 63
      - 71
      - 98
      3:
      - 13
      - 16
      - 23
      4: 3.11.7
      5: 0.16.1
      6: 4.26.1
      8:
      - 5
      13: linux-x86_64
